[settings]
rootDirectory = "backend"

[build]
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300   # allow time for startup warmup
restartPolicyType = "ON_FAILURE"
