export interface ParkInfo {
  name: string
  city: string
  opened: number
  surface: 'Grass' | 'Turf' | 'Hybrid'
  roof: 'Open' | 'Retractable' | 'Dome'
  capacity: number
  /** Distances in feet: LF, LCF, CF, RCF, RF */
  dimensions: { lf: number; lcf: number; cf: number; rcf: number; rf: number }
  /** Wall heights in feet: LF, CF, RF */
  wallHeights: { lf: number; cf: number; rf: number }
  elevation: number  // feet above sea level
  windNotes: string
  specialFeatures: string[]
}

export const PARK_DATA: Record<string, ParkInfo> = {
  ARI: {
    name: 'Chase Field',
    city: 'Phoenix, AZ',
    opened: 1998,
    surface: 'Grass',
    roof: 'Retractable',
    capacity: 48359,
    dimensions: { lf: 330, lcf: 374, cf: 407, rcf: 374, rf: 334 },
    wallHeights: { lf: 7.5, cf: 7.5, rf: 7.5 },
    elevation: 1082,
    windNotes: 'Roof typically closed in summer heat; eliminates wind when closed.',
    specialFeatures: ['Pool and hot tub in RF', 'Retractable roof', 'Air-conditioned when closed', 'High elevation (1,082 ft)'],
  },
  ATL: {
    name: 'Truist Park',
    city: 'Cumberland, GA',
    opened: 2017,
    surface: 'Grass',
    roof: 'Open',
    capacity: 41149,
    dimensions: { lf: 335, lcf: 380, cf: 400, rcf: 375, rf: 325 },
    wallHeights: { lf: 6, cf: 8, rf: 8 },
    elevation: 971,
    windNotes: 'Prevailing winds from southwest; relatively sheltered suburban location.',
    specialFeatures: ['The Battery entertainment district adjacent', 'Large RF overhang', 'Multiple open concourses'],
  },
  BAL: {
    name: 'Oriole Park at Camden Yards',
    city: 'Baltimore, MD',
    opened: 1992,
    surface: 'Grass',
    roof: 'Open',
    capacity: 44970,
    dimensions: { lf: 333, lcf: 364, cf: 400, rcf: 373, rf: 318 },
    wallHeights: { lf: 7, cf: 7, rf: 7 },
    elevation: 43,
    windNotes: 'Chesapeake Bay winds can swirl; generally favors hitters in warm months.',
    specialFeatures: ['B&O Warehouse beyond RF', 'Asymmetric LF (natural slope)', 'Template for retro ballparks'],
  },
  BOS: {
    name: 'Fenway Park',
    city: 'Boston, MA',
    opened: 1912,
    surface: 'Grass',
    roof: 'Open',
    capacity: 37755,
    dimensions: { lf: 310, lcf: 379, cf: 390, rcf: 380, rf: 302 },
    wallHeights: { lf: 37, cf: 17, rf: 5 },
    elevation: 19,
    windNotes: 'Atlantic sea breezes variable; LF winds can hold up fly balls or add carry.',
    specialFeatures: ['Green Monster (37 ft LF wall)', 'Pesky Pole (RF foul pole, 302 ft)', 'Triangle in CF (390 ft notch)', 'Oldest active MLB park (1912)'],
  },
  CHC: {
    name: 'Wrigley Field',
    city: 'Chicago, IL',
    opened: 1914,
    surface: 'Grass',
    roof: 'Open',
    capacity: 41649,
    dimensions: { lf: 355, lcf: 368, cf: 400, rcf: 368, rf: 353 },
    wallHeights: { lf: 11, cf: 11, rf: 11 },
    elevation: 595,
    windNotes: 'Lake Michigan winds critical — out to CF is historically homer-friendly; in from the lake suppresses offense dramatically.',
    specialFeatures: ['Ivy-covered brick outfield wall', 'Hand-operated scoreboard', 'Bleachers beyond fence', 'Second oldest active park (1914)'],
  },
  CWS: {
    name: 'Guaranteed Rate Field',
    city: 'Chicago, IL',
    opened: 1991,
    surface: 'Grass',
    roof: 'Open',
    capacity: 40615,
    dimensions: { lf: 330, lcf: 377, cf: 400, rcf: 372, rf: 335 },
    wallHeights: { lf: 8, cf: 8, rf: 8 },
    elevation: 595,
    windNotes: 'Southside Chicago; wind often blows out to LF from the west.',
    specialFeatures: ['Classic sightlines', 'Exploding scoreboard'],
  },
  CIN: {
    name: 'Great American Ball Park',
    city: 'Cincinnati, OH',
    opened: 2003,
    surface: 'Grass',
    roof: 'Open',
    capacity: 42319,
    dimensions: { lf: 328, lcf: 370, cf: 404, rcf: 370, rf: 325 },
    wallHeights: { lf: 12, cf: 12, rf: 12 },
    elevation: 489,
    windNotes: 'Ohio River location; summer heat and wind off river can carry balls.',
    specialFeatures: ['Riverfront Ohio River backdrop', 'Launch pad sections in CF', 'Highly hitter-friendly power alleys'],
  },
  CLE: {
    name: 'Progressive Field',
    city: 'Cleveland, OH',
    opened: 1994,
    surface: 'Grass',
    roof: 'Open',
    capacity: 34830,
    dimensions: { lf: 325, lcf: 370, cf: 405, rcf: 375, rf: 325 },
    wallHeights: { lf: 19, cf: 19, rf: 8 },
    elevation: 653,
    windNotes: 'Lake Erie influence; cold spring winds suppress offense.',
    specialFeatures: ['Variable LF wall height (up to 19 ft)', 'Large foul territory'],
  },
  COL: {
    name: 'Coors Field',
    city: 'Denver, CO',
    opened: 1995,
    surface: 'Grass',
    roof: 'Open',
    capacity: 50445,
    dimensions: { lf: 347, lcf: 390, cf: 415, rcf: 375, rf: 350 },
    wallHeights: { lf: 8, cf: 8, rf: 8 },
    elevation: 5200,
    windNotes: 'Mile-high altitude (5,200 ft) — ball travels ~10% farther. Downtown Denver adds thermals.',
    specialFeatures: ['Highest park in MLB (5,200 ft)', 'Humidor used since 2002 to reduce flight', 'Deep outfield to compensate altitude', 'Purple row at exactly 1 mile elevation'],
  },
  DET: {
    name: 'Comerica Park',
    city: 'Detroit, MI',
    opened: 2000,
    surface: 'Grass',
    roof: 'Open',
    capacity: 41083,
    dimensions: { lf: 345, lcf: 370, cf: 420, rcf: 365, rf: 330 },
    wallHeights: { lf: 8, cf: 8, rf: 8 },
    elevation: 583,
    windNotes: 'Deep CF (420 ft) suppresses HR; cold spring games from Lake Huron.',
    specialFeatures: ['Tiger statues at entry', 'Deep center field fountain', 'Ferris wheel inside park'],
  },
  HOU: {
    name: 'Minute Maid Park',
    city: 'Houston, TX',
    opened: 2000,
    surface: 'Grass',
    roof: 'Retractable',
    capacity: 41168,
    dimensions: { lf: 315, lcf: 362, cf: 409, rcf: 373, rf: 326 },
    wallHeights: { lf: 7, cf: 7, rf: 7 },
    elevation: 43,
    windNotes: 'Roof typically closed due to Houston heat; no wind factor when closed.',
    specialFeatures: ['Crawford Boxes (LF short porch, 315 ft)', 'Hill and flagpole in CF (in play)', 'Retractable roof'],
  },
  KC: {
    name: 'Kauffman Stadium',
    city: 'Kansas City, MO',
    opened: 1973,
    surface: 'Grass',
    roof: 'Open',
    capacity: 37903,
    dimensions: { lf: 330, lcf: 387, cf: 410, rcf: 387, rf: 330 },
    wallHeights: { lf: 9, cf: 9, rf: 9 },
    elevation: 909,
    windNotes: 'Great Plains winds variable; can dramatically shift HR rates.',
    specialFeatures: ['Waterfall/fountain beyond outfield wall', 'Symmetrical design', 'One of few single-purpose stadiums'],
  },
  LAA: {
    name: 'Angel Stadium',
    city: 'Anaheim, CA',
    opened: 1966,
    surface: 'Grass',
    roof: 'Open',
    capacity: 45517,
    dimensions: { lf: 347, lcf: 370, cf: 396, rcf: 370, rf: 350 },
    wallHeights: { lf: 8, cf: 8, rf: 8 },
    elevation: 160,
    windNotes: 'Marine layer from Pacific; cool evening air suppresses carry. Santa Ana winds occasionally push opposite.',
    specialFeatures: ['Rock formation beyond CF', 'One of oldest current parks (opened 1966, renovated)', 'Large foul territory'],
  },
  LAD: {
    name: 'Dodger Stadium',
    city: 'Los Angeles, CA',
    opened: 1962,
    surface: 'Grass',
    roof: 'Open',
    capacity: 56000,
    dimensions: { lf: 330, lcf: 360, cf: 395, rcf: 375, rf: 330 },
    wallHeights: { lf: 4, cf: 8, rf: 4 },
    elevation: 512,
    windNotes: 'Marine layer from Pacific; Chavez Ravine hills create dead-air conditions, suppressing offense.',
    specialFeatures: ['Oldest park in NL West (1962)', 'Largest capacity in MLB (56,000)', 'Hillside setting with no obstructions', 'Chavez Ravine dead-air effect'],
  },
  MIA: {
    name: 'loanDepot Park',
    city: 'Miami, FL',
    opened: 2012,
    surface: 'Grass',
    roof: 'Retractable',
    capacity: 37442,
    dimensions: { lf: 344, lcf: 386, cf: 407, rcf: 392, rf: 335 },
    wallHeights: { lf: 8, cf: 8, rf: 8 },
    elevation: 10,
    windNotes: 'Roof usually closed; no wind. Florida humidity when open.',
    specialFeatures: ['Retractable roof', 'Home Run sculpture in CF (replaced 2021)', 'Air conditioned when closed'],
  },
  MIL: {
    name: 'American Family Field',
    city: 'Milwaukee, WI',
    opened: 2001,
    surface: 'Grass',
    roof: 'Retractable',
    capacity: 41900,
    dimensions: { lf: 344, lcf: 371, cf: 400, rcf: 374, rf: 345 },
    wallHeights: { lf: 8, cf: 8, rf: 8 },
    elevation: 634,
    windNotes: 'Roof often open; Lake Michigan winds create cold, ball-suppressing conditions in spring.',
    specialFeatures: ['Retractable roof (but often open)', 'Bernie Brewer slide in RF', 'Sausage race tradition'],
  },
  MIN: {
    name: 'Target Field',
    city: 'Minneapolis, MN',
    opened: 2010,
    surface: 'Grass',
    roof: 'Open',
    capacity: 38544,
    dimensions: { lf: 339, lcf: 377, cf: 404, rcf: 367, rf: 328 },
    wallHeights: { lf: 8, cf: 8, rf: 23 },
    elevation: 830,
    windNotes: 'Cold Minnesota spring/fall suppresses offense; downtown location creates wind tunnels.',
    specialFeatures: ['23-ft RF wall', 'Outdoor park in cold-weather market', 'Limestone exterior'],
  },
  NYM: {
    name: 'Citi Field',
    city: 'New York, NY',
    opened: 2009,
    surface: 'Grass',
    roof: 'Open',
    capacity: 41922,
    dimensions: { lf: 335, lcf: 379, cf: 408, rcf: 383, rf: 330 },
    wallHeights: { lf: 8, cf: 8, rf: 8 },
    elevation: 18,
    windNotes: 'Flushing, Queens; variable ocean winds. Historically pitcher-friendly despite renovations expanding OF.',
    specialFeatures: ['Jackie Robinson Rotunda entrance', 'Originally very large outfield (renovated 2012+)', 'Apple in CF'],
  },
  NYY: {
    name: 'Yankee Stadium',
    city: 'New York, NY',
    opened: 2009,
    surface: 'Grass',
    roof: 'Open',
    capacity: 54251,
    dimensions: { lf: 318, lcf: 399, cf: 408, rcf: 385, rf: 314 },
    wallHeights: { lf: 8, cf: 8, rf: 8 },
    elevation: 55,
    windNotes: 'The Bronx; winds off the Hudson can push flies into or out of the short RF porch.',
    specialFeatures: ['Short RF porch (314 ft)', 'Monument Park beyond CF fence', 'Second largest capacity in AL'],
  },
  OAK: {
    name: 'Oakland Coliseum',
    city: 'Oakland, CA',
    opened: 1966,
    surface: 'Grass',
    roof: 'Open',
    capacity: 46765,
    dimensions: { lf: 330, lcf: 362, cf: 400, rcf: 362, rf: 330 },
    wallHeights: { lf: 8, cf: 8, rf: 8 },
    elevation: 24,
    windNotes: 'Bay Area marine layer and cold evening winds famously suppress offense. Called "The Black Hole."',
    specialFeatures: ['Dual-use stadium (Raiders formerly shared)', 'Foul territory largest in MLB', 'Marine layer deadens balls'],
  },
  PHI: {
    name: 'Citizens Bank Park',
    city: 'Philadelphia, PA',
    opened: 2004,
    surface: 'Grass',
    roof: 'Open',
    capacity: 42792,
    dimensions: { lf: 329, lcf: 369, cf: 401, rcf: 369, rf: 330 },
    wallHeights: { lf: 6, cf: 6, rf: 6 },
    elevation: 46,
    windNotes: 'Variable; summer heat and humidity carry balls. One of more hitter-friendly parks in NL.',
    specialFeatures: ['Ashburn Alley concourse', 'Liberty Bell home run feature', 'Consistently ranked hitter-friendly'],
  },
  PIT: {
    name: 'PNC Park',
    city: 'Pittsburgh, PA',
    opened: 2001,
    surface: 'Grass',
    roof: 'Open',
    capacity: 38747,
    dimensions: { lf: 325, lcf: 383, cf: 399, rcf: 375, rf: 320 },
    wallHeights: { lf: 6, cf: 10, rf: 21 },
    elevation: 715,
    windNotes: 'Allegheny River nearby; prevailing winds from the SW. Considered neutral.',
    specialFeatures: ['21-ft RF wall', 'Roberto Clemente Bridge backdrop', 'Frequently ranked most beautiful park in MLB'],
  },
  SD: {
    name: 'Petco Park',
    city: 'San Diego, CA',
    opened: 2004,
    surface: 'Grass',
    roof: 'Open',
    capacity: 42445,
    dimensions: { lf: 336, lcf: 367, cf: 396, rcf: 391, rf: 322 },
    wallHeights: { lf: 8, cf: 8, rf: 8 },
    elevation: 19,
    windNotes: 'Pacific Ocean marine layer and cool ocean breezes heavily suppress offense. One of strongest pitcher parks.',
    specialFeatures: ['Deep RF gap (391 ft)', 'Western Metal Supply building in LF corner (in play)', 'Park in the Park lawn area in CF', 'Marine layer = natural pitcher advantage'],
  },
  SF: {
    name: 'Oracle Park',
    city: 'San Francisco, CA',
    opened: 2000,
    surface: 'Grass',
    roof: 'Open',
    capacity: 41915,
    dimensions: { lf: 339, lcf: 364, cf: 399, rcf: 421, rf: 309 },
    wallHeights: { lf: 8, cf: 8, rf: 24 },
    elevation: 8,
    windNotes: 'San Francisco Bay winds (typically in from CF) dramatically suppress HR. Historically one of strongest pitcher parks.',
    specialFeatures: ['McCovey Cove (SF Bay in RF)', '24-ft RF wall', 'Splash Hit HR into the Bay', 'Bay winds = extreme pitcher advantage'],
  },
  SEA: {
    name: 'T-Mobile Park',
    city: 'Seattle, WA',
    opened: 1999,
    surface: 'Grass',
    roof: 'Retractable',
    capacity: 47929,
    dimensions: { lf: 331, lcf: 390, cf: 401, rcf: 381, rf: 326 },
    wallHeights: { lf: 8, cf: 8, rf: 8 },
    elevation: 17,
    windNotes: 'Roof closed in rain; Pacific NW marine air suppresses offense when open.',
    specialFeatures: ['Retractable roof', 'Deep LCF power alley', 'Edgar Martinez Drive namesake'],
  },
  STL: {
    name: 'Busch Stadium',
    city: 'St. Louis, MO',
    opened: 2006,
    surface: 'Grass',
    roof: 'Open',
    capacity: 45538,
    dimensions: { lf: 336, lcf: 375, cf: 400, rcf: 375, rf: 335 },
    wallHeights: { lf: 8, cf: 8, rf: 8 },
    elevation: 466,
    windNotes: 'Mississippi River location; humidity in summer, cold in April. Relatively neutral park.',
    specialFeatures: ['Gateway Arch visible beyond CF', 'Symmetrical layout', 'Third Busch Stadium (opened 2006)'],
  },
  TB: {
    name: 'Tropicana Field',
    city: 'St. Petersburg, FL',
    opened: 1990,
    surface: 'Turf',
    roof: 'Dome',
    capacity: 25000,
    dimensions: { lf: 315, lcf: 370, cf: 404, rcf: 370, rf: 322 },
    wallHeights: { lf: 11, cf: 6, rf: 11 },
    elevation: 43,
    windNotes: 'Completely enclosed dome — no wind factor whatsoever.',
    specialFeatures: ['Only permanent dome in MLB', 'Artificial turf speeds ground balls', 'Catwalk rings (in play)', 'Rays tank with stingrays in OF concourse'],
  },
  TEX: {
    name: 'Globe Life Field',
    city: 'Arlington, TX',
    opened: 2020,
    surface: 'Grass',
    roof: 'Retractable',
    capacity: 40518,
    dimensions: { lf: 329, lcf: 372, cf: 407, rcf: 374, rf: 326 },
    wallHeights: { lf: 8, cf: 8, rf: 8 },
    elevation: 551,
    windNotes: 'Texas heat necessitates closed roof most games; fully air-conditioned interior.',
    specialFeatures: ['Largest retractable-roof venue in MLB', 'Air-conditioned interior', 'Built to replace Rangers Ballpark (due to heat)', 'First full season 2021 (COVID delayed 2020)'],
  },
  TOR: {
    name: 'Rogers Centre',
    city: 'Toronto, Ontario',
    opened: 1989,
    surface: 'Turf',
    roof: 'Retractable',
    capacity: 49282,
    dimensions: { lf: 328, lcf: 375, cf: 400, rcf: 375, rf: 328 },
    wallHeights: { lf: 10, cf: 10, rf: 10 },
    elevation: 249,
    windNotes: 'Roof usually closed; artificial turf boosts ground ball speed.',
    specialFeatures: ['Artificial turf', 'Retractable roof', 'CN Tower visible outside', 'Symmetrical dimensions'],
  },
  WSH: {
    name: 'Nationals Park',
    city: 'Washington, D.C.',
    opened: 2008,
    surface: 'Grass',
    roof: 'Open',
    capacity: 41339,
    dimensions: { lf: 336, lcf: 377, cf: 402, rcf: 370, rf: 335 },
    wallHeights: { lf: 8, cf: 8, rf: 8 },
    elevation: 10,
    windNotes: 'Anacostia River location; D.C. humidity in summer. Slight hitter lean.',
    specialFeatures: ['Presidents Race tradition', 'Anacostia River backdrop', 'Symmetrical modern design'],
  },
}

// Normalize abbreviation variants to canonical key
export const ABBR_TO_PARK_KEY: Record<string, string> = {
  ARI: 'ARI', AZ: 'ARI',
  ATH: 'OAK', OAK: 'OAK',
  CHW: 'CWS', CWS: 'CWS',
  KCR: 'KC', KC: 'KC',
  SDP: 'SD', SD: 'SD',
  SFG: 'SF', SF: 'SF',
  TBR: 'TB', TB: 'TB',
  WSN: 'WSH', WSH: 'WSH',
  TBD: 'TB',
}

export function getParkInfo(abbr: string): ParkInfo | undefined {
  const key = ABBR_TO_PARK_KEY[abbr] ?? abbr
  return PARK_DATA[key]
}
